server: 
   port: 3344
   
   
spring: 
   application:
    name: microservicecloud-config-3344
   cloud:
    config:
      server:
        git:
          uri: https://github.com/konglingze/microservicecloud-config.git
          #uri: https://github.com/zzyybs/microservicecloud-config.git