server:
  port: 8080

feign:
  hystrix:
    enabled: true
eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.edu:7001/eureka/,http://eureka7002.edu:7002/eureka/,http://eureka7003.edu:7003/eureka/  